import type { ModelProviderConfig } from "../domain/types";

export const providerRegistry: ModelProviderConfig[] = [
  {
    id: "openai",
    label: "OpenAI",
    apiKeyName: "OPENAI_API_KEY",
    defaultModel: "gpt-5",
    recommendedModels: ["gpt-5", "gpt-5-mini", "gpt-4.1", "gpt-4.1-mini"],
    capabilities: {
      text: true,
      vision: true,
      toolCalls: true,
      jsonSchema: true,
      local: false,
      streaming: true,
      maxContextTokens: 400_000,
    },
  },
  {
    id: "anthropic",
    label: "Anthropic",
    apiKeyName: "ANTHROPIC_API_KEY",
    defaultModel: "claude-sonnet-4-5",
    recommendedModels: ["claude-sonnet-4-5", "claude-opus-4-1", "claude-haiku-4-5"],
    capabilities: {
      text: true,
      vision: true,
      toolCalls: true,
      jsonSchema: true,
      local: false,
      streaming: true,
      maxContextTokens: 200_000,
    },
  },
  {
    id: "google",
    label: "Google Gemini",
    apiKeyName: "GEMINI_API_KEY",
    defaultModel: "gemini-2.5-pro",
    recommendedModels: ["gemini-2.5-pro", "gemini-2.5-flash", "gemini-2.0-flash"],
    capabilities: {
      text: true,
      vision: true,
      toolCalls: true,
      jsonSchema: true,
      local: false,
      streaming: true,
      maxContextTokens: 1_000_000,
    },
  },
  {
    id: "deepseek",
    label: "DeepSeek",
    apiKeyName: "DEEPSEEK_API_KEY",
    defaultModel: "deepseek-v4-pro",
    recommendedModels: ["deepseek-v4-pro", "deepseek-v4-flash", "deepseek-chat", "deepseek-reasoner"],
    capabilities: {
      text: true,
      vision: false,
      toolCalls: true,
      jsonSchema: true,
      local: false,
      streaming: true,
      maxContextTokens: 128_000,
    },
  },
  {
    id: "ollama",
    label: "Ollama",
    baseUrl: "http://127.0.0.1:11434",
    defaultModel: "qwen3-coder",
    recommendedModels: ["qwen3-coder", "deepseek-coder", "llama3.1"],
    capabilities: {
      text: true,
      vision: false,
      toolCalls: false,
      jsonSchema: true,
      local: true,
      streaming: true,
      maxContextTokens: 64_000,
    },
  },
  {
    id: "openrouter",
    label: "OpenRouter",
    baseUrl: "https://openrouter.ai/api/v1",
    apiKeyName: "OPENROUTER_API_KEY",
    defaultModel: "openai/gpt-5.1-codex",
    recommendedModels: ["openai/gpt-5.1-codex", "anthropic/claude-sonnet-4.5", "google/gemini-2.5-pro", "deepseek/deepseek-chat-v3.2"],
    capabilities: {
      text: true,
      vision: true,
      toolCalls: true,
      jsonSchema: true,
      local: false,
      streaming: true,
      maxContextTokens: 1_000_000,
    },
  },
  {
    id: "xai",
    label: "xAI",
    baseUrl: "https://api.x.ai/v1",
    apiKeyName: "XAI_API_KEY",
    defaultModel: "grok-4",
    recommendedModels: ["grok-4", "grok-4-fast", "grok-code-fast-1"],
    capabilities: {
      text: true,
      vision: true,
      toolCalls: true,
      jsonSchema: true,
      local: false,
      streaming: true,
      maxContextTokens: 256_000,
    },
  },
  {
    id: "mistral",
    label: "Mistral",
    baseUrl: "https://api.mistral.ai/v1",
    apiKeyName: "MISTRAL_API_KEY",
    defaultModel: "devstral-large-latest",
    recommendedModels: ["devstral-large-latest", "mistral-large-latest", "codestral-latest", "magistral-medium-latest"],
    capabilities: {
      text: true,
      vision: true,
      toolCalls: true,
      jsonSchema: true,
      local: false,
      streaming: true,
      maxContextTokens: 256_000,
    },
  },
  {
    id: "groq",
    label: "Groq",
    baseUrl: "https://api.groq.com/openai/v1",
    apiKeyName: "GROQ_API_KEY",
    defaultModel: "qwen/qwen3-coder-480b-a35b-instruct",
    recommendedModels: ["qwen/qwen3-coder-480b-a35b-instruct", "openai/gpt-oss-120b", "llama-3.3-70b-versatile"],
    capabilities: {
      text: true,
      vision: false,
      toolCalls: true,
      jsonSchema: true,
      local: false,
      streaming: true,
      maxContextTokens: 128_000,
    },
  },
  {
    id: "qwen",
    label: "Qwen / DashScope",
    baseUrl: "https://dashscope.aliyuncs.com/compatible-mode/v1",
    apiKeyName: "DASHSCOPE_API_KEY",
    defaultModel: "qwen3-max",
    recommendedModels: ["qwen3-max", "qwen3-coder-plus", "qwen-plus", "qwen-turbo"],
    capabilities: {
      text: true,
      vision: true,
      toolCalls: true,
      jsonSchema: true,
      local: false,
      streaming: true,
      maxContextTokens: 128_000,
    },
  },
  {
    id: "kimi",
    label: "Kimi / Moonshot",
    baseUrl: "https://api.moonshot.cn/v1",
    apiKeyName: "MOONSHOT_API_KEY",
    defaultModel: "kimi-k2-turbo-preview",
    recommendedModels: ["kimi-k2-turbo-preview", "kimi-k2-thinking-turbo", "moonshot-v1-128k", "moonshot-v1-32k"],
    capabilities: {
      text: true,
      vision: true,
      toolCalls: true,
      jsonSchema: true,
      local: false,
      streaming: true,
      maxContextTokens: 128_000,
    },
  },
  {
    id: "siliconflow",
    label: "SiliconFlow",
    baseUrl: "https://api.siliconflow.cn/v1",
    apiKeyName: "SILICONFLOW_API_KEY",
    defaultModel: "deepseek-ai/DeepSeek-V3.2",
    recommendedModels: ["deepseek-ai/DeepSeek-V3.2", "Qwen/Qwen3-Coder-480B-A35B-Instruct", "zai-org/GLM-4.6", "moonshotai/Kimi-K2-Instruct"],
    capabilities: {
      text: true,
      vision: true,
      toolCalls: true,
      jsonSchema: true,
      local: false,
      streaming: true,
      maxContextTokens: 256_000,
    },
  },
  {
    id: "zhipu",
    label: "Zhipu / GLM",
    baseUrl: "https://open.bigmodel.cn/api/paas/v4",
    apiKeyName: "ZHIPU_API_KEY",
    defaultModel: "glm-4.6",
    recommendedModels: ["glm-4.6", "glm-4.5", "glm-4-plus", "glm-4-air"],
    capabilities: {
      text: true,
      vision: true,
      toolCalls: true,
      jsonSchema: true,
      local: false,
      streaming: true,
      maxContextTokens: 128_000,
    },
  },
  {
    id: "fixture",
    label: "Fixture",
    baseUrl: "fixture://offline",
    defaultModel: "fixture-coder",
    recommendedModels: ["fixture-coder"],
    capabilities: {
      text: true,
      vision: false,
      toolCalls: true,
      jsonSchema: true,
      local: true,
      streaming: true,
      maxContextTokens: 16_000,
    },
  },
];

export function findProvider(providerId: string) {
  return providerRegistry.find((provider) => provider.id === providerId);
}
